### ISSUE TITLE
Sanity checks may hinder users when custom templates are used.

### ISSUE THREAD

**Issue by defeatedbylife** [ansible-middleware/jws#167] opened 2022-08-16 09:03 UTC
##### SUMMARY

If a customer reuses jws_listen_https_enabled(tomcat_listen_https_enabled) variable in their custom server.xml template, but uses .pem certificates instead of keystores, the sanity checks will kick in and fail the installation. I have not tested it yet. Not a big issue, but may cause confusion.

##### ISSUE TYPE
 - Bug Report

##### COLLECTION VERSION

```
1.1.1
```

**Comment by rpelisse** [comment] 2022-08-16 09:05
@defeatedbylife Can you copy and paste the playbook you used? I'll add a scenario to jws-dot to reproduce this. Thanks!

**Comment by rpelisse** [comment] 2022-08-18 15:14
@csutherl any thoughts on this one?

**Comment by csutherl** [comment] 2022-08-18 18:55
Yeah, we're going to need a change to the [template](https://github.com/ansible-middleware/jws-ansible-playbook/blob/main/roles/jws/templates/server.xml.j2#L119) to allow for certificate/key pairs, in addition to java keystores, because both are valid options. We're actually using a deprecated option (see https://tomcat.apache.org/tomcat-9.0-doc/config/http.html#SSL_Support_-_Connector_-_NIO_and_NIO2_(deprecated)) and should use `certificateFile` or `certificateKeystoreFile`, depending on whether or not the user specifies a keystore or keypair.

Looking at the check though, it'll only fail because the connector won't be running unless you provide a keystore...so that part is working as expected ;)

**Comment by rpelisse** [comment] 2022-08-19 07:20
> Yeah, we're going to need a change to the [template](https://github.com/ansible-middleware/jws-ansible-playbook/blob/main/roles/jws/templates/server.xml.j2#L119) to allow for certificate/key pairs, in addition to java keystores, because both are valid options.

So, we discussed that, a while back, with George and we agreed that we should NOT try to make the default template support to many use case. The rational behind that is that, anyway, most users modifying the server.xml will need to provide their own template. That's why we have the override_server_xml feature. In fact, this template is just here for demo purpose, so that it works out of the box. 

Along the same lines, I would not implement sanity checks for this kind of configuration, because we'll end up doing a lot of if stmt, trying to guess which feature the user is using or not. 

If a user provides its own templates and that it's configuration requires /etc/blah file to be deploy, his playbook should take care of deploy this file (the way user want) and he should add an appropriate assert: block to check that all is in place. 

> We're actually using a deprecated option....

Then we should update our template to use the recommanded option (and maybe do sanity check based if the vars are defined). 
@csutherl can you copy'n'paste here the recommanded configuration? I'll update template.

**Comment by csutherl** [comment] 2022-09-01 12:43
The example from the tomcat `server.xml` is:

```
    <!-- Define an SSL/TLS HTTP/1.1 Connector on port 8443
         This connector uses the NIO implementation. The default
         SSLImplementation will depend on the presence of the APR/native
         library and the useOpenSSL attribute of the AprLifecycleListener.
         Either JSSE or OpenSSL style configuration may be used regardless of
         the SSLImplementation selected. JSSE style configuration is used below.
    -->
    <!--
    <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
               maxThreads="150" SSLEnabled="true">
        <SSLHostConfig>
            <Certificate certificateKeystoreFile="conf/localhost-rsa.jks"
                         type="RSA" />
        </SSLHostConfig>
    </Connector>
    -->
```

**Comment by rpelisse** [comment] 2022-09-01 15:43
Fixed by [PR196](https://github.com/ansible-middleware/jws/pull/196)

**Closed** 2022-09-02 12:19 UTC
